name: YNOV pipeline CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      server-python-version:
        description: 'Python version to use on server'
        required: true
        default: '3.11'
        options:
          #- "3.9"
          #- "3.10"
          - "3.11"

jobs:    
  build:
    strategy:
      matrix:
        version: 
        #- '3.9'
        #- '3.10'
        - '3.11'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Lint with flake8
        run: |
          flake8 .

      #- name: Lint with black
      #  run: |
      #    black . --check


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage-badge

      - name: Test with Pytest
        run: |
          pytest --doctest-modules --ignore=server.py
      
      - name: Run test coverage
        run: |
          pytest --cov=. . --doctest-modules --ignore=server.py
          rm coverage.svg
          coverage-badge -o coverage.svg 

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: MEP
        run: echo "MEP on server"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Test if website is up 🚀
        run: |
          pip install requests
          python -c "import requests; exit(1) if requests.get('https://www.google.fr').status_code != 200 else exit(0)"

  post-on-slack:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Slack message
        run: echo "Pipeline finish with success, or not..."
