name: YNOV pipeline CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
      

jobs:    
  build:
    strategy:
      matrix:
        version: ['3.9', '3.10', '3.11']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Lint with flake8
        run: |
          flake8 .

      #- name: Lint with black
      #  run: |
      #    black . --check


  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test with Pytest
        run: |
          pytest --doctest-modules --ignore=server.py

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: MEP
        run: echo "MEP on server"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Test if website is up 🚀
        run: |
          pip install requests
          python -c "import requests; exit(1) if requests.get('https://www.google.fr').status_code != 200 else exit(0)"

  finish:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Finish
        run: echo "Pipeline finish with success."
