name: Continuous integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: lint with flake8
        run: |
          flake8 .

      - name: lint with black
        run: |
          black . --check
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: test with pytest
        run: |
          pytest --doctest-modules --ignore=server.py
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: MEP
        run: echo "MEP on server"

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Test if website is up
        run: |
          pip install requests
          python -c "import requests; exit(1) if requests.get('https://www.google.com').status_code != 200 else exit(0)"
